"""empty message

Revision ID: 9f6b191ea0b4
Revises: d5b3ae05791c
Create Date: 2020-08-27 23:46:55.511906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6b191ea0b4'
down_revision = 'd5b3ae05791c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('cid', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_comment_cid'), 'comment', ['cid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_cid'), table_name='comment')
    op.drop_column('comment', 'cid')
    # ### end Alembic commands ###
