"""empty message

Revision ID: a994bdc7fd2b
Revises: 9f6b191ea0b4
Create Date: 2020-08-28 09:03:19.219571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a994bdc7fd2b'
down_revision = '9f6b191ea0b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weibo', sa.Column('n_thumb', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weibo', 'n_thumb')
    # ### end Alembic commands ###
