"""empty message

Revision ID: c2c954c3650c
Revises: 69ff7e637569
Create Date: 2020-08-29 15:34:00.666459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c954c3650c'
down_revision = '69ff7e637569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('fid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'fid')
    )
    op.add_column('user', sa.Column('n_fans', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('n_follow', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'n_follow')
    op.drop_column('user', 'n_fans')
    op.drop_table('follow')
    # ### end Alembic commands ###
