"""empty message

Revision ID: d5b3ae05791c
Revises: e4cd0f9364db
Create Date: 2020-08-27 21:59:21.041186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b3ae05791c'
down_revision = 'e4cd0f9364db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('wid', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_uid'), 'comment', ['uid'], unique=False)
    op.create_index(op.f('ix_comment_wid'), 'comment', ['wid'], unique=False)
    op.add_column('user', sa.Column('avatar', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    op.drop_index(op.f('ix_comment_wid'), table_name='comment')
    op.drop_index(op.f('ix_comment_uid'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
